### ISSUE TITLE
MBON OBIS 2018 dates are wrong

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/zoo-taxonomy-to-darwin-core#5]
reported by @sebastiandig : wrong dates were used sample identification date used as actual date.

Need to update the data on OBIS.

**Comment by sebastiandig** [comment]
sent email directly, will need to parse out the column names as I did not do much on fixing those.

**Comment by sebastiandig** [comment]
I have a script that can help us get into the right direction in terms of formatting. This takes  the current version and without manually editing, convert to a more useful format.

It uses two files from the your `gdrive`. You would just need to download them and direct to where they are located. 
I will put this in an R directory within this for you too look at.

**Comment by sebastiandig** [comment]
Here is the code: [zoo_jamie_fix](https://github.com/USF-IMARS/zoo-taxonomy-to-darwin-core/blob/master/R/zoo_jamie_fix.R)

Let me know if you need explanation or something for me to modify. The taxa names are left as is currently.

**Comment by 7yl4r** [comment]
@albenson-usgs : can we temporarily pull the MBON Zooplankton dataset out of OBIS? We need to remove the published data that is inaccurate until we can fix the issue.

**Comment by 7yl4r** [comment]
from sebastian on Jan 13:

> You should be able to find a new .Rmd file called "old_zoo_fix". You will need two files from the google drive (https://drive.google.com/drive/folders/1FcyUnXjqIeh2XF7uhuuvKL8eYGSaJVvZ) which is outlined in the Rmd file.

**Comment by sebastiandig** [comment]
Hi @7yl4r,

I've started working on cleaning up the previous data. You can take a look at the code here: [fix_prev_zoo_data.qmd](https://github.com/sebastiandig/obis_zooplankton_setup/blob/main/Rmd/fix_prev_zoo_data.qmd)

It bascially reads all the metadata and zooplankton data, then merges the two together. The species list would still need to be mapped to WoRMS, but I think you have that started. Then I would need to see which columns names match what I use to create an OBIS event and change the names to match. 

Let me know if you have any questions so far.

**Comment by 7yl4r** [comment]
new file for IPT

[occurrences.csv](https://github.com/USF-IMARS/zoo-taxonomy-to-darwin-core/files/11237356/occurrences.csv)
